language: node_js
node_js:
  - 10
services:
  - docker
addons:
  apt:
    packages:
      # Updating Docker.
      - docker-ce

install:
  - echo "Overriding npm install becuase we are using Docker."

jobs:
  include:
    - stage: "Tests"
      script: docker-compose -f docker-compose.yml -f dc-development.yml run --rm -e NODE_ENV=test -e CI=true frontend npm run test:ci

    # Docker deployment only happen for "master" and "release" branches. Pull requesting to those branches also trigger this build unless disabled in Travis CI Settings.
    - stage: "Docker-Deployment"
      if: branch = master OR branch = release
      script: ./docker/helpers/dockerHubUpload.sh
