version: "3.4"

services:
  frontend:
    build:
      context: .
      # Building only upto dev stage.
      target: dev
    container_name: hb-frontend-container-dev
    image: hb-frontend-image-dev
    command: npm start
    ports:
      - "3000:3000"

    # Dynamic mounting. So hot reload & code editing can be done without building again and again.
    volumes:
      # Mounting Current host folder into container.
      - .:/app
      # Below is a workaround to prevent host node_modules from accidently getting mounted in container. So host node_module folder don't have no effect on container.
      # Useful when want to use node/npm both outside container for test/lint, OR CI envoroments, etc.
      - frontendTempData:/usr/app/node_modules
