version: "3.4"

services:
  frontend:
    environment:
      # Getting env. variable directly from host enviroment OR .env file and pass them into container.
      - NODE_ENV
      - REACT_APP_API_BASEURL

      - DOCKER_USERNAME
      - DOCKER_PASSWORD

      - CYPRESS_PROJECT_ID
      - CYPRESS_RECORD_KEY

      - CODECOV_TOKEN

# Custom volume to store database data premenetly.
volumes:
  ? frontendTempData # For holding container's node_modules without clashing with host node_modules. (See dc-development.yml)
